---

- name: Create directory /opt/infra-binaries/temp
  file:
    path: /opt/infra-binaries/temp
    state: directory
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_id }}'
    mode: 0755
  become: yes

##################################################
# Binaries
##################################################
- block: #Install binaries

    - name: Download and untar flannel and etcdctl binaries
      unarchive:
        src: "{{ item }}"
        dest: /opt/infra-binaries/temp/
        remote_src: yes    
      with_items:
        - '{{ flannel_url }}'
        - '{{ etcd_url }}'

    - name: Move Flannel binary to /opt/infra-binaries
      copy:
        remote_src: yes
        src: /opt/infra-binaries/temp/flanneld
        dest: /opt/infra-binaries
        mode: 0744

    - name: Move etcdctl binary to /opt/infra-binaries
      copy:
        remote_src: yes
        src: /opt/infra-binaries/temp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}
        dest: /opt/infra-binaries
        mode: 0744
      with_items:
        - etcdctl

  tags: [binaries]

##################################################
# Services
##################################################
- block:

    - name: Move services files
      template:
        src: flannel.service.j2
        dest: /etc/systemd/system/flannel.service
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        mode: '0644'
        backup: yes
      become: yes
      notify:
      - restart flannel

  
  tags: [services]
